import type { FinalReport, UserReport } from '../simulation/types'
import { formatBrl, formatNumber, formatPercent } from '../utils/format'

interface FinalReportProps { report: FinalReport | null; onExportJson: () => void; onExportCsv: () => void }

function statusClass(user: UserReport): string {
  if (user.status === 'SUPERÁVIT') return 'tone-positive'
  if (user.status === 'DÉFICIT') return 'tone-negative'
  if (user.status === 'NÃO ATENDIDO') return 'tone-warning'
  return 'tone-neutral'
}

export function FinalReport({ report, onExportJson, onExportCsv }: FinalReportProps) {
  if (!report) return <section className="report-placeholder panel-surface"><div className="report-placeholder-icon">▤</div><div><p className="eyebrow">Relatório final</p><h2>O fechamento aparece aqui ao parar uma simulação</h2><p>Execute algumas rodadas para consolidar a situação dos dez usuários, o retorno do mercado e o gráfico comparativo.</p></div></section>
  const maxUms = Math.max(1, ...report.users.map((user) => user.ums))
  const maxBrl = Math.max(1, ...report.users.map((user) => Math.abs(user.brl)))
  return <section className="report-section">
    <div className="section-heading"><div><p className="eyebrow">Relatório final · rodada {formatNumber(report.round)}</p><h2>O que aconteceu com cada usuário</h2></div><div className="report-actions"><button className="button button-quiet" type="button" onClick={onExportCsv}>↓ CSV</button><button className="button button-secondary" type="button" onClick={onExportJson}>↓ JSON</button></div></div>
    <div className="report-metrics"><div><span>Solicitados</span><strong>{formatNumber(report.totals.servicesRequested)}</strong></div><div><span>Executados</span><strong>{formatNumber(report.totals.servicesExecuted)}</strong></div><div><span>Não atendidos</span><strong className="negative-text">{formatNumber(report.totals.servicesUnmet)}</strong></div><div><span>UMS reconhecida</span><strong>{formatNumber(report.totals.umsGenerated)}</strong></div><div><span>PoUW rejeitado</span><strong className="warning-text">{formatNumber(report.totals.umsRejected)}</strong></div><div><span>MWC disponível</span><strong className="amber-text">{formatNumber(report.market.mwcAvailable)}</strong></div><div><span>MWC reconvertido</span><strong>{formatNumber(report.market.mwcReconverted)}</strong></div><div><span>BRL movimentado</span><strong>{formatBrl(report.market.brlVolume)}</strong></div></div>
    <div className="report-grid">
      <article className="panel-surface report-summary"><div className="report-summary-head"><span className="report-seal">✓</span><div><span>SIMULAÇÃO CONSOLIDADA</span><strong>{formatNumber(report.totals.servicesExecuted)} serviços processados</strong></div></div><div className="narrative-list">{report.narrative.map((line) => <p key={line}><span>—</span>{line}</p>)}</div><div className="report-warning">Modelo didático em memória. UMS, MWC e BRL são representações do protótipo e não constituem moeda, investimento ou operação financeira real.</div></article>
      <article className="panel-surface report-bars"><div className="chart-title"><div><span className="chart-kicker">COMPARATIVO FINAL</span><h3>Saldo UMS por usuário</h3></div><span className="chart-unit">rodada {formatNumber(report.round)}</span></div><div className="bar-list">{report.users.map((user) => <div className="bar-row" key={user.id}><div className="bar-label"><span>{user.id}</span><small>{formatPercent(user.profile)}</small></div><div className="bar-track"><div className="bar-fill" style={{ width: `${Math.max(2, (user.ums / maxUms) * 100)}%` }} /></div><strong>{formatNumber(user.ums)}</strong></div>)}</div></article>
    </div>
    <article className="panel-surface finance-panel"><div className="chart-title"><div><span className="chart-kicker amber">CONTABILIDADE DE REFERÊNCIA</span><h3>BRL positivo e negativo por usuário</h3></div><span className="chart-unit">posição final</span></div><div className="finance-bars">{report.users.map((user) => <div className="finance-row" key={user.id}><span>{user.id}</span><div className={`finance-track ${user.brl < 0 ? 'is-negative' : ''}`}><div className="finance-fill" style={{ width: `${Math.max(2, (Math.abs(user.brl) / maxBrl) * 100)}%` }} /></div><strong className={user.brl < 0 ? 'money-negative' : 'money-positive'}>{formatBrl(user.brl, true)}</strong></div>)}</div></article>
    <div className="panel-surface report-table-panel"><div className="section-heading compact"><div><p className="eyebrow">Fechamento por usuário</p><h3>Saldo, capacidade, PoUW e posição de mercado</h3></div><span className="table-note">ordenado por UMS</span></div><div className="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>UMS final</th><th>BRL</th><th>Gerado</th><th>Utilizado</th><th>PoUW rejeitado</th><th>Serviços / não</th><th>UMS não atendida</th><th>MWC criado</th><th>MWC usado</th><th>Status</th></tr></thead><tbody>{report.users.map((user) => <tr key={user.id}><td><strong>{user.id}</strong></td><td><span className={user.profile >= 0 ? 'profile-value is-positive' : 'profile-value is-negative'}>{formatPercent(user.profile)}</span></td><td><strong>{formatNumber(user.ums)}</strong></td><td><span className={user.brl < 0 ? 'money-negative' : user.brl > 0 ? 'money-positive' : 'money-neutral'}>{formatBrl(user.brl, true)}</span></td><td>{formatNumber(user.generated)}</td><td>{formatNumber(user.used)}</td><td className="warning-text">{formatNumber(user.invalid)}</td><td>{formatNumber(user.servicesExecuted)} <small className="unmet-inline">/ {formatNumber(user.servicesUnmet)}</small></td><td className="negative-text">{formatNumber(user.unmetUms)}</td><td>{formatNumber(user.mwcCreated)}</td><td>{formatNumber(user.mwcUsed)}</td><td><span className={`status-badge ${statusClass(user)}`}>{user.status}</span></td></tr>)}</tbody></table></div></div>
  </section>
}
